global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'oct-pdumon-sentry3'
    static_configs:
      - targets:
        - 10.91.1.11
        - 10.91.1.12
        - 10.91.1.21
        - 10.91.1.22
        - 10.91.1.91
        - 10.91.1.92
    metrics_path: /snmp
    params:
      module: [servertech_sentry3]
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 10.91.0.1:9116

  # Global exporter-level metrics
  - job_name: 'oct-prometheus-snmp'
    static_configs:
      - targets: ['10.91.0.1:9116']

  - job_name: 'oct-prometheus-ipmi'
    static_configs:
      - targets:
        - 10.0.1.1
        - 10.0.1.2
        - 10.0.1.3
        - 10.0.1.4
        - 10.0.1.6
        - 10.0.1.7
        - 10.0.1.8
        - 10.0.1.10
        - 10.0.1.11
        - 10.0.1.12
        - 10.0.1.13
        - 10.0.1.14
        - 10.0.1.15
        - 10.0.1.16
        - 10.0.1.17
        - 10.0.1.18
        - 10.0.1.19
        - 10.0.1.20
        - 10.0.1.21
        - 10.0.1.22
        - 10.0.1.23
        - 10.0.1.24
        - 10.0.1.100
        - 10.0.1.101
        - 10.0.1.102
        - 10.0.1.103
        - 10.0.1.104
        - 10.0.1.105
        - 10.0.1.106
        - 10.0.1.107
        - 10.0.1.108
        - 10.0.1.109
        - 10.0.1.110
        - 10.0.1.111
        - 10.0.1.112
        - 10.0.1.113
        - 10.0.1.114
        - 10.0.1.115
        - 10.0.2.0
        - 10.0.2.1
        - 10.0.2.2
        - 10.0.2.4
        - 10.0.2.5
        - 10.0.2.6
        - 10.0.2.7
        - 10.0.2.8
        - 10.0.2.9
        - 10.0.2.10
        - 10.0.2.12
        - 10.0.2.13
        - 10.0.2.14
        - 10.0.2.15
        - 10.0.2.16
        - 10.0.2.18
        - 10.0.2.19
        - 10.0.2.20
        - 10.0.2.21
        - 10.0.2.23
        - 10.0.2.24
        - 10.0.2.25
        - 10.0.2.26
        - 10.0.2.27
        - 10.0.2.30
        - 10.0.2.31
        - 10.0.2.32
        - 10.0.2.33
        - 10.0.2.34
        - 10.0.2.35
        - 10.0.2.36
        - 10.0.2.37
        - 10.0.3.0
        - 10.0.3.1
        - 10.0.3.2
        - 10.0.3.3
        - 10.0.3.4
        - 10.0.3.6
        - 10.0.3.7
        - 10.0.3.8
        - 10.0.3.9
        - 10.0.3.11
        - 10.0.3.12
        - 10.0.3.17
        - 10.0.3.19
        - 10.0.3.20
        - 10.0.3.21
        - 10.0.3.22
        - 10.0.3.24
        - 10.0.3.25
        - 10.0.3.26
        - 10.0.3.28
        - 10.0.3.31
        - 10.0.3.32
        - 10.0.3.33
        - 10.0.3.35
        - 10.0.3.36
        - 10.0.3.37
    params:
      module: ['default']
    metrics_path: /ipmi
    scheme: http
    relabel_configs:
    - source_labels: [__address__]
      separator: ;
      regex: (.*)
      target_label: __param_target
      replacement: ${1}
      action: replace
    - source_labels: [__param_target]
      separator: ;
      regex: (.*)
      target_label: instance
      replacement: ${1}
      action: replace
    - separator: ;
      regex: .*
      target_label: __address__
      replacement: 10.0.0.200:9290
      action: replace
