global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'oct-pdumon-sentry3'
    static_configs:
      - targets:
        - 10.91.1.11
        - 10.91.1.12
        - 10.91.1.21
        - 10.91.1.22
        - 10.91.1.91
        - 10.91.1.92
    metrics_path: /snmp
    params:
      module: [servertech_sentry3]
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 10.91.0.1:9116

  # Global exporter-level metrics
  - job_name: 'oct-prometheus-snmp'
    static_configs:
      - targets: ['10.91.0.1:9116']
